SistemaPedidos/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemaPedidos.Models;

namespace SistemaPedidos.Controllers
{
    public class PedidoController : Controller
    {
        [HttpGet]
        public IActionResult Registrar()
        {
            CarregarViewBag();
            return View();
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.ListaVendas = new PedidoModel().ListagemPedidos();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(PedidoModel pedido)
        {
            if (ModelState.IsValid)
            {
                pedido.GravarPedido();
                return RedirectToAction("Index");
                
            }
            CarregarViewBag();
            return View();
        }

        private void CarregarViewBag()
        {
            ViewBag.ListaClientes = new PedidoModel().RetornarListaClientes();
            ViewBag.ListaProdutos = new PedidoModel().RetornarListaProdutos();
        }
    }
}

SistemaPedidos/Views/Pedido/Excluir.cshtml
@{
    ViewData["Title"] = "Excluir";
}

<h2>Excluir</h2>

SistemaPedidos/Views/Pedido/Index.cshtml
<h2>Listagem de Pedidos</h2>

<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Registrar Pedido</button>
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Cliente</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>

        @{
            foreach (var item in (List<PedidoModel>)ViewBag.ListaVendas)
            {
                <tr>
                    <td>@item.IdPedido</td>
                    <td>@item.IdCliente</td>
                    <td>R$ @item.TotalPedido</td>
                </tr>
            }
        }
    </tbody>
</table>
<br />
<script>
    function Cadastrar()
    {
        window.location.href = "../Pedido/Registrar";

    }
</script>

SistemaPedidos/Views/Pedido/Registrar.cshtml
@model PedidoModel

<h2>Registrar um Pedido</h2>
<br />

<form asp-controller="Pedido" asp-action="Registrar">
    <input type="hidden" asp-for="IdPedido" value="@try { @ViewBag.Pedido.idPedido } catch { }" />

    <div class="form-group">
        <label>Cliente</label>
        <select asp-for="IdCliente" class="form-control" id="selCliente">

            <option value=""></option>
            @{
            foreach (var item in (List<ClienteModel>)ViewBag.ListaClientes)
            {
                <option value="@item.idCliente">@item.nomeCliente</option>
        }
            }
        </select>
        <span asp-validation-for="IdCliente" class="text-danger"></span>
    </div>

    <label>Produtos</label>
    <br /><br />
    <div class="form-group control-group">
        <div class="col-lg-4">

            <select class="form-control" id="selProduto" onchange="DefaultRentabilidade()" >
                <option value=""></option>
                @{
                    foreach (var item in (List<ProdutoModel>)ViewBag.ListaProdutos)
                    {
                        <option value="@item.IdProduto | @item.PrecoUnitarioProduto | @item.MultiploProduto">@item.DescProduto </option>
                    }
                }
            </select>

        </div>
        <div class="col-lg-2">
            <input type="text" class="form-control " id="txtValorProduto" data-mask="###0,00" data-mask-reverse="true" data-mask-maxlength="false" placeholder="Valor Unitário" />
        </div>
        <div class="col-lg-2">
            <input type="text" class="form-control" id="txtQuantidade" placeholder="Qtde" />
        </div>

        <div class="col-lg-2">
            <span id="spnRentab" class="label label-default">Rentabilidade</span>
        </div>

        <div class="col-lg-2">
            <button type="button" class="btn btn-block btn-primary" onclick="AdicionarProduto()" readonly>Adicionar</button>
        </div>
    </div>

    <br /><br />

    <table class="table table-bordered" id="tabelaProdutos">
        <thead>
            <tr>
                <td style="display:none;">Id</td>
                <td>Nome</td>
                <td>Quantidade</td>
                <td>Preço Unitário</td>
                <td>Total</td>
                <td>#</td>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
    <div class="row">
        <div class="col-lg-9">
        </div>
        <div class="col-lg-3">
            <div style="float:left">Total do Pedido R$ </div>
            <div style="float:left" id="totalPedido">0,00</div>
        </div>
    </div>

    <textarea style="display:none" asp-for="JsonItens" id="JsonItens"></textarea>
    <input type="hidden" asp-for="TotalPedido" id="txtTotal" />

    <button type="submit" class="btn btn-primary btn-success" onclick="RegistrarPedido();">Registrar</button>
    <button type="button" class="btn btn-primary btn-warning" onclick="Voltar();">Voltar</button>

</form>


<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/qunit/qunit-1.11.0.js"></script>
<script src="~/lib/jquery.mask.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script src="~/js/Pedido.js"></script>